# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlassian-cli" do
  name "atlassian-cli"
  desc "Atlassian CLI tool"
  homepage "https://github.com/ainoya/atlassian-cli"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlassian-cli"

  on_macos do
    on_arm do
      url "https://github.com/ainoya/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "92451baa773f6e8daffe546e090d97b79e57b6f62944bc716b83ad23fe04ee2e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ainoya/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_linux_amd64.tar.gz"
      sha256 "ca057f990bd48dcfe3d411e0e60fda61b1c3e748a139b5e9f0267c7f26647da5"
    end
  end

  # No zap stanza required
end
