# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlassian-cli" do
  name "atlassian-cli"
  desc "Atlassian CLI tool"
  homepage "https://github.com/ainoya/atlassian-cli"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlassian-cli"

  on_macos do
    on_arm do
      url "https://github.com/ainoya/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "2765d1ea7d0a9a5138f4f5d0fc168a984c91399be88a3fc3f3ea83bd6ed87d8a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ainoya/atlassian-cli/releases/download/v#{version}/atlassian-cli_#{version}_linux_amd64.tar.gz"
      sha256 "e1ed52546409bd6bf51fa091e6a9439ce96b333273fbf09194b980e3cd7af30d"
    end
  end

  # No zap stanza required
end
