# This file was generated by GoReleaser. DO NOT EDIT.
cask "esa-cli" do
  name "esa-cli"
  desc "Esa CLI tool"
  homepage "https://github.com/ainoya/esa-cli"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "esa-cli"

  on_macos do
    on_arm do
      url "https://github.com/ainoya/esa-cli/releases/download/v#{version}/esa-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "c6d2df06904993993cdd419d5189d4bbb55da73c4f013de4f70b43198d9a3421"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ainoya/esa-cli/releases/download/v#{version}/esa-cli_#{version}_linux_amd64.tar.gz"
      sha256 "51bd674368a9e0adeefc3ca52f65a22d2614c20c44a849fb664e85d4c4a53f99"
    end
  end

  # No zap stanza required
end
