# This file was generated by GoReleaser. DO NOT EDIT.
cask "esa-cli" do
  name "esa-cli"
  desc "Esa CLI tool"
  homepage "https://github.com/ainoya/esa-cli"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "esa-cli"

  on_macos do
    on_arm do
      url "https://github.com/ainoya/esa-cli/releases/download/v#{version}/esa-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "f7b921f112a19f5a350ace366fcaa6b6c3183c8517d48f46327567d4dee984cf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ainoya/esa-cli/releases/download/v#{version}/esa-cli_#{version}_linux_amd64.tar.gz"
      sha256 "ed8063c992c604a4b011b33fc9ff2298a2080be51ee31a112a3c2ceda67c5f87"
    end
  end

  # No zap stanza required
end
