# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-cli" do
  name "slack-cli"
  desc "Slack CLI tool"
  homepage "https://github.com/ainoya/slack-cli"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack-cli"

  on_macos do
    on_arm do
      url "https://github.com/ainoya/slack-cli/releases/download/v#{version}/slack-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "bf490ac65f0203bc0a120c766b41850acc64484b3038bb37824b19e5e88e2270"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ainoya/slack-cli/releases/download/v#{version}/slack-cli_#{version}_linux_amd64.tar.gz"
      sha256 "ed1b4e73b0c362531832be83d9523f048ca40e80688c382d328644d43437d8b9"
    end
  end

  # No zap stanza required
end
