# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-cli" do
  name "slack-cli"
  desc "Slack CLI tool"
  homepage "https://github.com/ainoya/slack-cli"
  version "0.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack-cli"

  on_macos do
    on_arm do
      url "https://github.com/ainoya/slack-cli/releases/download/v#{version}/slack-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "07a9f43801d7a43349e957a5988cc0ae0f16a7b5be1134c44fefcd6172fdd43f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ainoya/slack-cli/releases/download/v#{version}/slack-cli_#{version}_linux_amd64.tar.gz"
      sha256 "5e0a65a210eed30c4b6369195ab74831f76580efc76e2ee90b573d1a0e2905ae"
    end
  end

  # No zap stanza required
end
